#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Generate internal/buildinfo package based on git history.
This script creates a MoonBit package that exports build information constants.
"""

import subprocess
import sys
import json
import re
from pathlib import Path


def get_commit_count():
    """Get the total number of commits from the beginning of history to HEAD."""
    try:
        result = subprocess.run(
            ["git", "rev-list", "--count", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return int(result.stdout.strip())
    except subprocess.CalledProcessError as e:
        print(f"Error getting commit count: {e}", file=sys.stderr)
        return 0
    except ValueError as e:
        print(f"Error parsing commit count: {e}", file=sys.stderr)
        return 0


def get_commit_sha():
    """Get the short commit SHA of HEAD."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error getting commit SHA: {e}", file=sys.stderr)
        return "unknown"


def get_version_from_moon_mod(project_root):
    """Read version from moon.mod.json."""
    moon_mod_path = project_root / "moon.mod.json"
    try:
        with open(moon_mod_path, "r") as f:
            moon_mod = json.load(f)
            return moon_mod.get("version", "0.0.0")
    except (FileNotFoundError, json.JSONDecodeError, KeyError) as e:
        print(f"Error reading version from moon.mod.json: {e}", file=sys.stderr)
        return "0.0.0"


def extract_commit_sha_from_file(buildinfo_mbt):
    """Extract commit SHA from existing buildinfo.mbt file."""
    try:
        with open(buildinfo_mbt, "r") as f:
            content = f.read()
            # Look for the version string pattern
            import re

            match = re.search(
                r'let version_string : String = "[^"]+\.([a-f0-9]+)"', content
            )
            if match:
                return match.group(1)
    except FileNotFoundError:
        pass
    except Exception as e:
        print(f"Error reading existing buildinfo: {e}", file=sys.stderr)
    return None


def generate_buildinfo():
    """Generate the buildinfo package."""
    # Get project root (parent of scripts directory)
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    buildinfo_dir = project_root / "internal" / "buildinfo"

    # Create directory if it doesn't exist
    buildinfo_dir.mkdir(parents=True, exist_ok=True)

    # Get commit count, SHA, and version
    commit_count = get_commit_count()
    commit_sha = get_commit_sha()
    version = get_version_from_moon_mod(project_root)

    # Generate buildinfo.mbt
    version_string_mbt = buildinfo_dir / "version_string.mbt"

    # Check if file exists and has the same commit SHA
    existing_sha = extract_commit_sha_from_file(version_string_mbt)
    if existing_sha == commit_sha:
        print(
            f"Buildinfo already up-to-date (commit {commit_sha}), skipping regeneration"
        )
        return
    print(f"Updating buildinfo from commit {existing_sha} to {commit_sha}")

    content = f"""// Build Information
// This file is auto-generated by scripts/buildinfo.py
// Do not edit manually.

///|
/// Version string following semver format with build metadata
/// Format: MAJOR.MINOR.PATCH+BUILD_NUMBER.COMMIT_SHA
let version_string : String = "{version}+{commit_count}.{commit_sha}"
"""

    with open(version_string_mbt, "w") as f:
        f.write(content)

    # Generate .gitignore if it doesn't exist
    gitignore_path = buildinfo_dir / ".gitignore"
    if not gitignore_path.exists():
        with open(gitignore_path, "w") as f:
            f.write(f"{version_string_mbt.name}\n")

    # Generate moon.pkg if it doesn't exist
    pkg_json = buildinfo_dir / "moon.pkg"
    if not pkg_json.exists():
        pkg_content = f"""import {{
  "moonbitlang/core/json",
  "moonbitlang/core/strconv",
}}

options(
  is_main: false,
  "pre-build": [
    {{
      "command": "python3 scripts/buildinfo.py"
      "input": [ ],
      "output": "{version_string_mbt.name}",
    }},
  ],
)
"""
        with open(pkg_json, "w") as f:
            f.write(pkg_content)

    print(
        f"Generated buildinfo package with version = {version}+{commit_count}.{commit_sha}"
    )


if __name__ == "__main__":
    generate_buildinfo()
