///|
pub const Continue : String = "Continue"

///|
pub const SwitchingProtocols : String = "Switching Protocols"

///|
pub const Processing : String = "Processing"

///|
pub const EarlyHints : String = "Early Hints"

///|
pub const Ok : String = "OK"

///|
pub const Created : String = "Created"

///|
pub const Accepted : String = "Accepted"

///|
pub const NonAuthoritativeInformation : String = "Non-Authoritative Information"

///|
pub const NoContent : String = "No Content"

///|
pub const ResetContent : String = "Reset Content"

///|
pub const PartialContent : String = "Partial Content"

///|
pub const MultiStatus : String = "Multi-Status"

///|
pub const AlreadyReported : String = "Already Reported"

///|
pub const ImUsed : String = "IM Used"

///|
pub const MultipleChoices : String = "Multiple Choices"

///|
pub const MovedPermanently : String = "Moved Permanently"

///|
pub const Found : String = "Found"

///|
pub const SeeOther : String = "See Other"

///|
pub const NotModified : String = "Not Modified"

///|
pub const UseProxy : String = "Use Proxy"

///|
pub const TemporaryRedirect : String = "Temporary Redirect"

///|
pub const PermanentRedirect : String = "Permanent Redirect"

///|
pub const BadRequest : String = "Bad Request"

///|
pub const Unauthorized : String = "Unauthorized"

///|
pub const PaymentRequired : String = "Payment Required"

///|
pub const Forbidden : String = "Forbidden"

///|
pub const NotFound : String = "Not Found"

///|
pub const MethodNotAllowed : String = "Method Not Allowed"

///|
pub const NotAcceptable : String = "Not Acceptable"

///|
pub const ProxyAuthenticationRequired : String = "Proxy Authentication Required"

///|
pub const RequestTimeout : String = "Request Timeout"

///|
pub const Conflict : String = "Conflict"

///|
pub const Gone : String = "Gone"

///|
pub const LengthRequired : String = "Length Required"

///|
pub const PreconditionFailed : String = "Precondition Failed"

///|
pub const PayloadTooLarge : String = "Payload Too Large"

///|
pub const UriTooLong : String = "URI Too Long"

///|
pub const UnsupportedMediaType : String = "Unsupported Media Type"

///|
pub const RangeNotSatisfiable : String = "Range Not Satisfiable"

///|
pub const ExpectationFailed : String = "Expectation Failed"

///|
pub const ImATeapot : String = "I'm a teapot"

///|
pub const MisdirectedRequest : String = "Misdirected Request"

///|
pub const UnprocessableEntity : String = "Unprocessable Entity"

///|
pub const Locked : String = "Locked"

///|
pub const FailedDependency : String = "Failed Dependency"

///|
pub const TooEarly : String = "Too Early"

///|
pub const UpgradeRequired : String = "Upgrade Required"

///|
pub const PreconditionRequired : String = "Precondition Required"

///|
pub const TooManyRequests : String = "Too Many Requests"

///|
pub const RequestHeaderFieldsTooLarge : String = "Request Header Fields Too Large"

///|
pub const UnavailableForLegalReasons : String = "Unavailable For Legal Reasons"

///|
pub const InternalServerError : String = "Internal Server Error"

///|
pub const NotImplemented : String = "Not Implemented"

///|
pub const BadGateway : String = "Bad Gateway"

///|
pub const ServiceUnavailable : String = "Service Unavailable"

///|
pub const GatewayTimeout : String = "Gateway Timeout"

///|
pub const HttpVersionNotSupported : String = "HTTP Version Not Supported"

///|
pub const VariantAlsoNegotiates : String = "Variant Also Negotiates"

///|
pub const InsufficientStorage : String = "Insufficient Storage"

///|
pub const LoopDetected : String = "Loop Detected"

///|
pub const NotExtended : String = "Not Extended"

///|
pub const NetworkAuthenticationRequired : String = "Network Authentication Required"
